# Generated by Django 5.0.6 on 2024-06-23 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dep_id", models.IntegerField(primary_key=True, serialize=False)),
                ("dep_name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=60)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Attendance_status",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(default="pending for approval", max_length=30),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nss.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("des", models.TextField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nss.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event_Photos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="events")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nss.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "programme_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("program_name", models.CharField(max_length=65)),
                ("no_of_sems", models.IntegerField()),
                ("grad_level", models.CharField(max_length=10)),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nss.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="volunteer",
            fields=[
                ("volunteer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("status", models.CharField(default="active", max_length=20)),
                ("guard_name", models.CharField(max_length=25)),
                ("guard_mob_no", models.IntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=15
                    ),
                ),
                ("dob", models.DateField()),
                (
                    "year",
                    models.IntegerField(choices=[("1", "1"), ("2", "2"), ("3", "3")]),
                ),
                (
                    "community",
                    models.CharField(
                        choices=[
                            ("st", "ST"),
                            ("sc", "SC"),
                            ("general", "General"),
                            ("obc", "OBC"),
                        ],
                        max_length=15,
                    ),
                ),
                ("address", models.TextField()),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("a+", "A+"),
                            ("a-", "A-"),
                            ("b+", "B+"),
                            ("b-", "B-"),
                            ("o+", "O+"),
                            ("o-", "O-"),
                            ("ab+", "AB+"),
                            ("ab-", "AB-"),
                        ],
                        max_length=15,
                    ),
                ),
                ("height", models.IntegerField()),
                (
                    "unit",
                    models.IntegerField(choices=[("1", "1"), ("2", "2"), ("3", "3")]),
                ),
                ("weight", models.IntegerField()),
                ("mobile_no", models.IntegerField()),
                ("Email_id", models.EmailField(max_length=254)),
                ("year_of_enrollment", models.IntegerField()),
                ("cultural_talents", models.TextField()),
                ("hobbies", models.TextField()),
                ("roll_no", models.IntegerField(null=True)),
                ("image", models.ImageField(default="", upload_to="volunteers")),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nss.programme"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("Attendance_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("no_of_hours", models.IntegerField()),
                (
                    "Attendance_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nss.attendance_status",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nss.event"
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="nss.volunteer",
                    ),
                ),
            ],
        ),
    ]
