# Generated by Django 5.0.6 on 2024-06-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance_status",
            name="unit",
            field=models.IntegerField(default=1),
        ),
    ]
