# Generated by Django 5.0.6 on 2024-06-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0002_attendance_status_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance_status",
            name="unit",
            field=models.IntegerField(),
        ),
    ]
