# Generated by Django 5.0.6 on 2024-06-25 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0003_alter_attendance_status_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance_status",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventattendances",
                to="nss.event",
            ),
        ),
        migrations.AlterField(
            model_name="event_details",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventdetails",
                to="nss.event",
            ),
        ),
        migrations.AlterField(
            model_name="event_photos",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventphotos",
                to="nss.event",
            ),
        ),
    ]
