# Generated by Django 5.0.6 on 2024-06-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0004_alter_attendance_status_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event_details",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="event_details",
            name="start_time",
        ),
    ]
