# Generated by Django 5.0.6 on 2024-07-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0008_remove_camp_attendance_no_of_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp_event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=60)),
                ('des', models.TextField()),
                ('date', models.DateField()),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss.camp')),
            ],
        ),
        migrations.AlterField(
            model_name='camp_event_photos',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_eventphotos', to='nss.camp_event'),
        ),
        migrations.DeleteModel(
            name='Camp_event_details',
        ),
    ]
