# Generated by Django 5.0.6 on 2024-07-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0009_camp_event_alter_camp_event_photos_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_details',
            name='expense',
            field=models.TextField(null=True),
        ),
    ]
